/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.echoer.hotgen;

import org.labcrypto.hottentot.runtime.RequestHandler;


public abstract class AbstractEchoService implements EchoService {	
  public RequestHandler makeRequestHandler() {
    return new EchoRequestHandler(this);
  }
  public long getServiceId() {
    return 3639300462L;
  }
}
