/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 24-08-2016 11:09:22
 * Name: big_file_transfer_service_impl.h
 * Description:
 *   This file contains definitions of sample stub.
 ******************************************************************/
 
#ifndef _ORG_LABCRYPTO_HOTTENTOT_EXAMPLES_BIGFILETRANSFER__BIG_FILE_TRANSFER_SERVICE_IMPL_H_
#define _ORG_LABCRYPTO_HOTTENTOT_EXAMPLES_BIGFILETRANSFER__BIG_FILE_TRANSFER_SERVICE_IMPL_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include "../service/abstract_big_file_transfer_service.h"


namespace org {
namespace labcrypto {
namespace hottentot {
namespace examples {
namespace bigfiletransfer {
  class BigFileTransferServiceImpl : public ::org::labcrypto::hottentot::examples::bigfiletransfer::service::AbstractBigFileTransferService {
  public:
    BigFileTransferServiceImpl() {}
    virtual ~BigFileTransferServiceImpl() {}
  public:
    virtual void OnInit();
    virtual void OnShutdown();
    virtual void SendBigFile(
      ::org::labcrypto::hottentot::ByteArray &fileData, 
      ::org::labcrypto::hottentot::Utf8String &fileName, 
      ::org::labcrypto::hottentot::Boolean &out, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
    );
  };
} // END OF NAMESPACE bigfiletransfer
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org

#endif