/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date:
 * Name:
 * Description:
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.client;

import ir.ntnaeem.hottentot.examples.listtest.hotgen.ListTestService;
import ir.ntnaeem.hottentot.examples.listtest.hotgen.ListTestServiceProxyBuilder;
import ir.ntnaeem.hottentot.examples.listtest.hotgen.Message;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Main {
  public static void main(String[] args) throws IOException {
    ir.ntnaeem.hottentot.runtime.config.Config.setMainArgs(args);
    final ListTestService listtestProxy = ListTestServiceProxyBuilder.create("127.0.0.1", 8080);
    //
    ArrayList<Short> numbers = new ArrayList<>();
    numbers.add((short) 1);
    numbers.add((short) 2);
    listtestProxy.addNumbers(numbers);
    //
    ArrayList<String> names = new ArrayList<>();
    names.add("name-1");
    names.add("name-2");
    listtestProxy.addNames(names);
    //
    Message message = new Message();
    message.setValue("MSG-TEST");
    listtestProxy.addMessage(message);
    //
    System.out.println("-----------------------------------");
    System.out.println("get messages method call");
    List<Message> messages = listtestProxy.getMessages();
    for (Message message1 : messages) {
      System.out.println(message.getValue());
    }
    //
    System.out.println("-----------------------------------");
    System.out.println("get names method call");
    for (String name : listtestProxy.getNames()) {
      System.out.println(name);
    }
    //use server methods on proxies
  }
}