/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.echoer;

import java.io.IOException;

import ir.ntnaeem.hottentot.examples.echoer.hotgen.EchoService;
import ir.ntnaeem.hottentot.examples.echoer.hotgen.EchoServiceProxyBuilder;



public class Main {
  public static void main(String[] args) throws IOException {
    org.labcrypto.hottentot.runtime.config.Config.setMainArgs(args);
    final EchoService echoProxy = EchoServiceProxyBuilder.create("127.0.0.1", 8080);

    //use server methods on proxies
  }
}