/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.tech.hotgen;

import ir.ntnaeem.hottentot.runtime.RequestHandler;

public abstract class AbstractTechService implements TechService {	
  public RequestHandler makeRequestHandler() {
    return new TechRequestHandler(this);
  }
  public long getServiceId() {
    return 3424918921L;
  }
}
