/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package example.generated.abc.xyz.hotgen;

import ir.ntnaeem.hottentot.runtime.Service;
import java.util.List;

public interface AuthenticationService extends Service {
  Token authenticate(Credential credential,DateTime datetime);

}
