/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package example.generated.abc.xyz.hotgen;

public class CalculatorServiceProxyBuilder {

  public static CalculatorService create(String host, int port) {
    return new CalculatorServiceProxy(host,port);
  }

  public static void destroy() {
    //TODO
  }
}
