/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package ir.ntnaeem.hottentot.examples.tech.hotgen;

import ir.ntnaeem.hottentot.runtime.Service;
import java.util.List;

public interface TechService extends Service {
  void report(String message);
  short getSerial();

}
