/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.tech.hotgen;

public class TechServiceProxyBuilder {

  public static TechService create(String host, int port) {
    return new TechServiceProxy(host,port);
  }

  public static void destroy() {
    //TODO
  }
}
