/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package hotgen;

import ir.ntnaeem.hottentot.runtime.RequestHandler;

public abstract class AbstractTestService implements TestService {	
  public RequestHandler makeRequestHandler() {
    return new TestRequestHandler(this);
  }
  public long getServiceId() {
    return 3840930520L;
  }
}
