/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 10-02-2016 11:35:21
 * Name: apache_license_manager_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "apache_license_manager_service_proxy_builder.h"
#include "apache_license_manager_service_proxy.h"


namespace org {
namespace apache {
namespace tests {
namespace proxy {
  ApacheLicenseManagerService*
  ApacheLicenseManagerServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new ApacheLicenseManagerServiceProxy(host, port);
  }
  void
  ApacheLicenseManagerServiceProxyBuilder::Destroy(ApacheLicenseManagerService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE tests
} // END OF NAMESPACE apache
} // END OF NAMESPACE org