/***********************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 01:32:49
 * Name: authentication_service.h
 * Description:
 *   This file contains definition of the interface used by proxies.
 ***********************************************************************/

#ifndef _EXAMPLE_GENERATED_ABC_XYZ__PROXY__AUTHENTICATION_SERVICE_H_
#define _EXAMPLE_GENERATED_ABC_XYZ__PROXY__AUTHENTICATION_SERVICE_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>

#include "../token.h"
#include "../credential.h"
#include "../date_time.h"


namespace example {
namespace generated {
namespace abc {
namespace xyz {
namespace proxy {
  class AuthenticationService {
  public:
     AuthenticationService() {}
     virtual ~AuthenticationService() {}
  public:
    virtual void Authenticate(
      ::example::generated::abc::xyz::Credential &credential, 
      ::example::generated::abc::xyz::DateTime &datetime, 
      ::example::generated::abc::xyz::Token &out
    ) = 0;
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE xyz
} // END OF NAMESPACE abc
} // END OF NAMESPACE generated
} // END OF NAMESPACE example

#endif