/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 10-02-2016 03:06:23
 * Name: authentication_service_proxy.h
 * Description:
 *   This file contains definition of the proxy class.
 ***************************************************************/

#ifndef _EXAMPLE_GENERATED_ABC_XYZ__PROXY__AUTHENTICATION_SERVICE_PROXY_H_
#define _EXAMPLE_GENERATED_ABC_XYZ__PROXY__AUTHENTICATION_SERVICE_PROXY_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/proxy/proxy.h>

#include "authentication_service.h"


namespace example {
namespace generated {
namespace abc {
namespace xyz {
class Token;
class Credential;
class DateTime;
namespace proxy {
  class AuthenticationServiceProxy : public AuthenticationService, 
    public ::naeem::hottentot::runtime::proxy::Proxy {
  public:
    AuthenticationServiceProxy(std::string host, uint32_t port) 
      : ::naeem::hottentot::runtime::proxy::Proxy(host, port) {}
    virtual ~AuthenticationServiceProxy() {}
  public:
    virtual void Authenticate(
      ::example::generated::abc::xyz::Credential &credential, 
      ::example::generated::abc::xyz::DateTime &datetime, 
      ::example::generated::abc::xyz::Token &out
    );
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE xyz
} // END OF NAMESPACE abc
} // END OF NAMESPACE generated
} // END OF NAMESPACE example

#endif