/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 10-02-2016 03:06:23
 * Name: authentication_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "authentication_service_proxy_builder.h"
#include "authentication_service_proxy.h"


namespace example {
namespace generated {
namespace abc {
namespace xyz {
namespace proxy {
  AuthenticationService*
  AuthenticationServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new AuthenticationServiceProxy(host, port);
  }
  void
  AuthenticationServiceProxyBuilder::Destroy(AuthenticationService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE xyz
} // END OF NAMESPACE abc
} // END OF NAMESPACE generated
} // END OF NAMESPACE example