/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 02:12:01
 * Name: phone_manager_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "phone_manager_service_proxy_builder.h"
#include "phone_manager_service_proxy.h"


namespace ir {
namespace ntnaeem {
namespace services {
namespace proxy {
  PhoneManagerService*
  PhoneManagerServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new PhoneManagerServiceProxy(host, port);
  }
  void
  PhoneManagerServiceProxyBuilder::Destroy(PhoneManagerService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE services
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir