/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 01:32:49
 * Name: tech_service_proxy.h
 * Description:
 *   This file contains definition of the proxy class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_HOTTENTOT_EXAMPLES_TECH__PROXY__TECH_SERVICE_PROXY_H_
#define _IR_NTNAEEM_HOTTENTOT_EXAMPLES_TECH__PROXY__TECH_SERVICE_PROXY_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/proxy/proxy.h>

#include "tech_service.h"


namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace tech {

namespace proxy {
  class TechServiceProxy : public TechService, 
    public ::naeem::hottentot::runtime::proxy::Proxy {
  public:
    TechServiceProxy(std::string host, uint32_t port) 
      : ::naeem::hottentot::runtime::proxy::Proxy(host, port) {}
    virtual ~TechServiceProxy() {}
  public:
    virtual void Report(
      ::naeem::hottentot::runtime::types::Utf8String &message
    );
    virtual void GetSerial(
      ::naeem::hottentot::runtime::types::Int16 &out
    );
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE tech
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif