/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 06-02-2016 03:48:37
 * Name: token.h
 * Description:
 *   This file contains definition of Token class.
 ***************************************************************/

#ifndef _NAEEM_HOTTENTOT_EXAMPLES_AUTH__TOKEN_H_
#define _NAEEM_HOTTENTOT_EXAMPLES_AUTH__TOKEN_H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>


namespace naeem {
namespace hottentot {
namespace examples {
namespace auth {
  class Token : public ::naeem::hottentot::runtime::Serializable {
  public:
    Token() {}
    Token(const Token &);
    Token(Token *);
    virtual ~Token() {}
  public:
    inline ::naeem::hottentot::runtime::types::Utf8String GetValue() const {
      return value_;
    }
    inline void SetValue(::naeem::hottentot::runtime::types::Utf8String value) {
      value_ = value;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::naeem::hottentot::runtime::types::Utf8String value_;
  };
} // END OF NAMESPACE auth
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE naeem

#endif