/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 01-02-2016 01:45:06
 * Name: echo_service_client.h
 * Description:
 *   This file contains a sample client.
 ******************************************************************/

#include <iostream>

#include <naeem/hottentot/runtime/configuration.h>
#include <naeem/hottentot/runtime/logger.h>
#include <naeem/hottentot/runtime/proxy/proxy_runtime.h>

#include "../echo_request.h"
#include "../echo_response.h"
#include "../echo_service.h"
#include "../proxy/echo_service_proxy_builder.h"


int 
main(int argc, char **argv) {
  try {
    ::naeem::hottentot::runtime::Logger::Init();  
    ::naeem::hottentot::runtime::proxy::ProxyRuntime::Init(argc, argv);
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "Proxy runtime is initialized." << std::endl;
    }
    ::ir::ntnaeem::hottentot::examples::win32::echo::EchoService *proxy = 
        ::ir::ntnaeem::hottentot::examples::win32::echo::proxy::EchoServiceProxyBuilder::Create("127.0.0.1", 2000);
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "Proxy object is created." << std::endl;
    }
    //--------------------------------------------------
    ::ir::ntnaeem::hottentot::examples::win32::echo::EchoRequest req;
    ::ir::ntnaeem::hottentot::examples::win32::echo::EchoResponse response;
    req.SetName("Kamran");
    proxy->DoEcho(req, response);
    std::cout << "Response: " << response.GetMessage().ToStdString() << std::endl;
    //--------------------------------------------------
    ::ir::ntnaeem::hottentot::examples::win32::echo::proxy::EchoServiceProxyBuilder::Destroy(proxy);
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "Proxy object is destroyed." << std::endl;
    }
    // Delete allocated objects
    std::cin.get();
  } catch (...) {
    ::naeem::hottentot::runtime::Logger::GetOut() << "Error." << std::endl;
    return 1;
  }
  return 0;
}
