/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 30-01-2016 08:21:47
 * Name: credential.h
 * Description:
 *   This file contains definition of Credential class.
 ***************************************************************/

#ifndef _HOTGEN__CREDENTIAL_H_
#define _HOTGEN__CREDENTIAL_H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>


namespace hotgen {
  class Credential : public ::naeem::hottentot::runtime::Serializable {
  public:
    Credential() {}
    ~Credential() {}
  public:
    inline ::naeem::hottentot::runtime::types::Utf8String GetUsername() const {
      return username_;
    }
    inline void SetUsername(::naeem::hottentot::runtime::types::Utf8String username) {
      username_ = username;
    }
    inline ::naeem::hottentot::runtime::types::Utf8String GetPassword() const {
      return password_;
    }
    inline void SetPassword(::naeem::hottentot::runtime::types::Utf8String password) {
      password_ = password;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::naeem::hottentot::runtime::types::Utf8String username_;
    ::naeem::hottentot::runtime::types::Utf8String password_;
  };
} // END OF NAMESPACE hotgen

#endif