/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 30-01-2016 08:21:47
 * Name: data_wrapper.h
 * Description:
 *   This file contains definition of DataWrapper class.
 ***************************************************************/

#ifndef _HOTGEN__DATA_WRAPPER_H_
#define _HOTGEN__DATA_WRAPPER_H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>


namespace hotgen {
  class DataWrapper : public ::naeem::hottentot::runtime::Serializable {
  public:
    DataWrapper() {}
    ~DataWrapper() {}
  public:
    inline ::naeem::hottentot::runtime::types::Utf8String GetValue() const {
      return value_;
    }
    inline void SetValue(::naeem::hottentot::runtime::types::Utf8String value) {
      value_ = value;
    }
    inline ::naeem::hottentot::runtime::types::ByteArray GetDigi() const {
      return digi_;
    }
    inline void SetDigi(::naeem::hottentot::runtime::types::ByteArray digi) {
      digi_ = digi;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::naeem::hottentot::runtime::types::Utf8String value_;
    ::naeem::hottentot::runtime::types::ByteArray digi_;
  };
} // END OF NAMESPACE hotgen

#endif