/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 01-02-2016 01:45:06
 * Name: echo_response.h
 * Description:
 *   This file contains definition of EchoResponse class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_HOTTENTOT_EXAMPLES_WIN32_ECHO__ECHO_RESPONSE_H_
#define _IR_NTNAEEM_HOTTENTOT_EXAMPLES_WIN32_ECHO__ECHO_RESPONSE_H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>


namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace win32 {
namespace echo {
  class EchoResponse : public ::naeem::hottentot::runtime::Serializable {
  public:
    EchoResponse() {}
    ~EchoResponse() {}
  public:
    inline ::naeem::hottentot::runtime::types::Utf8String GetMessage() const {
      return message_;
    }
    inline void SetMessage(::naeem::hottentot::runtime::types::Utf8String message) {
      message_ = message;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::naeem::hottentot::runtime::types::Utf8String message_;
  };
} // END OF NAMESPACE echo
} // END OF NAMESPACE win32
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif