/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package ir.ntnaeem.hottentot.examples.echoer;

import org.labcrypto.hottentot.runtime.Service;


public interface EchoService extends Service {
  ResponseMessage echoMessage(RequestMessage req);

}
