/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.hotgen.server;

import ir.ntnaeem.hottentot.runtime.Service;
import ir.ntnaeem.hottentot.runtime.ServiceRuntime;
import java.io.IOException;

public class Main {
  public static void main(String[] args) throws IOException {
    ir.ntnaeem.hottentot.runtime.config.Config.setMainArgs(args);
    ir.ntnaeem.hottentot.runtime.config.Config.setConfigPropertiesFromConfigFile();
    ServiceRuntime serviceRuntime = new ServiceRuntime();
    Service managementService = new ManagementImpl();
    serviceRuntime.register("127.0.0.1",8080, managementService);
    Service reportingService = new ReportingImpl();
    serviceRuntime.register("127.0.0.1",8080, reportingService);
    Service monitoringService = new MonitoringImpl();
    serviceRuntime.register("127.0.0.1",8080, monitoringService);

    serviceRuntime.start();
  }
}



