/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 30-01-2016 08:21:47
 * Name: test_service_proxy_builder.h
 * Description:
 *   This file contains definition of the proxy builder class.
 ******************************************************************/

#ifndef _HOTGEN__PROXY__TEST_SERVICE_PROXY_BUILDER_H_
#define _HOTGEN__PROXY__TEST_SERVICE_PROXY_BUILDER_H_

#include <stdint.h>
#include <string>


namespace hotgen {
class TestService;
namespace proxy {
  class TestServiceProxyBuilder {
  public:
    static TestService* Create(std::string /* host */, uint32_t /* port */);
    static void Destroy(TestService *);
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE hotgen

#endif