/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 30-01-2016 08:21:47
 * Name: test_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "test_service_proxy_builder.h"
#include "test_service_proxy.h"


namespace hotgen {
namespace proxy {
  TestService*
  TestServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new TestServiceProxy(host, port);
  }
  void
  TestServiceProxyBuilder::Destroy(TestService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE hotgen