/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 30-01-2016 08:21:47
 * Name: test_service_proxy.h
 * Description:
 *   This file contains definition of the proxy class.
 ***************************************************************/

#ifndef _HOTGEN__PROXY__TEST_SERVICE_PROXY_H_
#define _HOTGEN__PROXY__TEST_SERVICE_PROXY_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/proxy/proxy.h>

#include "../test_service.h"


namespace hotgen {
class Token;
class Credential;
class DataWrapper;
class StringWrapper;
class SampleStruct;
class Result;
namespace proxy {
  class TestServiceProxy : public ::hotgen::TestService, 
    public ::naeem::hottentot::runtime::proxy::Proxy {
  public:
    TestServiceProxy(std::string host, uint32_t port) 
      : ::naeem::hottentot::runtime::proxy::Proxy(host, port) {}
    virtual ~TestServiceProxy() {}
  public:
    virtual void Auth(::hotgen::Credential &credential, ::naeem::hottentot::runtime::types::List< ::hotgen::Token> &);
    virtual void Test(::naeem::hottentot::runtime::types::List< ::hotgen::DataWrapper> &);
    virtual void Test2(::naeem::hottentot::runtime::types::List< ::hotgen::StringWrapper> &);
    virtual void Test3(::hotgen::StringWrapper &);
    virtual void Test4(::hotgen::DataWrapper &);
    virtual void Test5(::naeem::hottentot::runtime::types::List< ::hotgen::StringWrapper> &inputList, ::hotgen::DataWrapper &);
    virtual void Test6(::naeem::hottentot::runtime::types::List< ::hotgen::DataWrapper> &inputs, ::hotgen::DataWrapper &);
    virtual void Test7(::hotgen::SampleStruct &);
    virtual void Test8(::hotgen::StringWrapper &str, ::hotgen::StringWrapper &);
    virtual void Test9(::hotgen::SampleStruct &sample, ::hotgen::Result &);
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE hotgen

#endif