/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 02-05-2016 05:11:23
 * Name: calculator_service_impl.h
 * Description:
 *   This file contains definitions of sample stub.
 ******************************************************************/
 
#ifndef _IR_NTNAEEM_HOTTENTOT_EXAMPLES_CALC__CALCULATOR_SERVICE_IMPL_H_
#define _IR_NTNAEEM_HOTTENTOT_EXAMPLES_CALC__CALCULATOR_SERVICE_IMPL_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include "../service/abstract_calculator_service.h"


namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace calc {
  class CalculatorServiceImpl : public ::ir::ntnaeem::hottentot::examples::calc::service::AbstractCalculatorService {
  public:
    CalculatorServiceImpl() {}
    virtual ~CalculatorServiceImpl() {}
  public:
    virtual void OnInit();
    virtual void OnShutdown();
    virtual void Add(
      ::org::labcrypto::hottentot::UInt16 &a, 
      ::org::labcrypto::hottentot::UInt16 &b, 
      ::org::labcrypto::hottentot::UInt16 &out, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
    );
    virtual void Mul(
      ::org::labcrypto::hottentot::Int16 &a, 
      ::org::labcrypto::hottentot::Int16 &b, 
      ::org::labcrypto::hottentot::Int16 &out, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
    );
  };
} // END OF NAMESPACE calc
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif