/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 16-01-2016 01:33:10
 * Name: echo_service_impl.h
 * Description:
 *   This file contains definitions of sample stub.
 ******************************************************************/
 
#ifndef _IR_NTNAEEM_HOTTENTOT_EXAMPLES_ECHOER__ECHO_SERVICE_IMPL_H_
#define _IR_NTNAEEM_HOTTENTOT_EXAMPLES_ECHOER__ECHO_SERVICE_IMPL_H_

#include <stdint.h>
#include <string>

#include "../gen/service/abstract_echo_service.h"


namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace echoer {
  class EchoServiceImpl : public ::ir::ntnaeem::hottentot::examples::echoer::service::AbstractEchoService {
  public:
    EchoServiceImpl() {}
    virtual ~EchoServiceImpl() {}
  public:
    virtual void OnInit();
    virtual void OnShutdown();
    virtual void EchoMessage(::ir::ntnaeem::hottentot::examples::echoer::RequestMessage &req, ::ir::ntnaeem::hottentot::examples::echoer::ResponseMessage &out);
  };
} // END OF NAMESPACE echoer
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif
