/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 24-08-2016 11:09:22
 * Name: big_file_transfer_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <org/labcrypto/hottentot/runtime/request.h>
#include <org/labcrypto/hottentot/runtime/response.h>

#include "big_file_transfer_service_request_handler.h"
#include "abstract_big_file_transfer_service.h"
#include "big_file_transfer_service.h"



namespace org {
namespace labcrypto {
namespace hottentot {
namespace examples {
namespace bigfiletransfer {
namespace service {
  void 
  BigFileTransferServiceRequestHandler::HandleRequest(::org::labcrypto::hottentot::runtime::Request &request, ::org::labcrypto::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 361284543) {
      ::org::labcrypto::hottentot::examples::bigfiletransfer::service::AbstractBigFileTransferService *serviceObject = 
        dynamic_cast< ::org::labcrypto::hottentot::examples::bigfiletransfer::service::AbstractBigFileTransferService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::org::labcrypto::hottentot::ByteArray fileData;
      fileData.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      ::org::labcrypto::hottentot::Utf8String fileName;
      fileName.Deserialize(request.GetArgumentData(1), request.GetArgumentLength(1));
      /*
       * Calling service method
       */
      ::org::labcrypto::hottentot::runtime::service::HotContext hotContext;
      
      ::org::labcrypto::hottentot::Boolean result;
      try {
        serviceObject->SendBigFile(fileData, fileName, result, hotContext);
      } catch (std::exception &e) {
        hotContext.SetFaultyResponse(e.what(), 50);
      } catch (...) {
        hotContext.SetFaultyResponse("Unknown server side exception.", 51);
      }
      /*
       * Serializiation of returned object
       */
      unsigned char *serializedData = 0;
      uint32_t serializedDataLength = 0;
      if (hotContext.GetResponseStatusCode() == 0) {
        serializedData = result.Serialize(&serializedDataLength);
      } else {
        ::org::labcrypto::hottentot::Utf8String faultMessage(hotContext.GetFaultMessage());
        serializedData = faultMessage.Serialize(&serializedDataLength);
      }
      response.SetStatusCode(hotContext.GetResponseStatusCode());
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE bigfiletransfer
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org