/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 08-10-2016 01:21:15
 * Name: echo_service_impl.cc
 * Description:
 *   This file contains empty implementation of sample stub.
 ******************************************************************/
 
#include <org/labcrypto/hottentot/runtime/configuration.h>
#include <org/labcrypto/hottentot/runtime/logger.h>
#include <org/labcrypto/hottentot/runtime/utils.h>

#include "echo_service_impl.h"

#include "../request_message.h"
#include "../response_message.h"


namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace echoer {
  void
  EchoServiceImpl::OnInit() {
    // TODO: Called when service is initializing.
  }
  void
  EchoServiceImpl::OnShutdown() {
    // TODO: Called when service is shutting down.
  }
  void
  EchoServiceImpl::EchoMessage(
    ::ir::ntnaeem::hottentot::examples::echoer::RequestMessage &req, 
    ::ir::ntnaeem::hottentot::examples::echoer::ResponseMessage &out, 
    ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
  ) {
    if (::org::labcrypto::hottentot::runtime::Configuration::Verbose()) {
      ::org::labcrypto::hottentot::runtime::Logger::GetOut() << 
        "[" << ::org::labcrypto::hottentot::runtime::Utils::GetCurrentUTCTimeString() << "]: " <<
          "EchoServiceImpl::EchoMessage() is called." << std::endl;
    }
    // TODO
  }
} // END OF NAMESPACE echoer
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir