/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package naeem.hottentot.examples.auth.hotgen;

import ir.ntnaeem.hottentot.runtime.RequestHandler;

public abstract class AbstractAuthenticateService implements AuthenticateService {	
  public RequestHandler makeRequestHandler() {
    return new AuthenticateRequestHandler(this);
  }
  public long getServiceId() {
    return 1500029818L;
  }
}
