/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package naeem.hottentot.examples.auth.hotgen;

import ir.ntnaeem.hottentot.runtime.Argument;
import ir.ntnaeem.hottentot.runtime.Proxy;
import ir.ntnaeem.hottentot.runtime.Request;
import ir.ntnaeem.hottentot.runtime.Response;
import ir.ntnaeem.hottentot.runtime.TcpClient;
import ir.ntnaeem.hottentot.runtime.exception.HottentotRuntimeException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientConnectException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientReadException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientWriteException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientCloseException;
import ir.ntnaeem.hottentot.runtime.factory.ProtocolFactory;
import ir.ntnaeem.hottentot.runtime.factory.TcpClientFactory;
import ir.ntnaeem.hottentot.runtime.protocol.Protocol;
import ir.ntnaeem.hottentot.serializerHelper.PDTSerializer;
import ir.ntnaeem.hottentot.serializerHelper.PDTDeserializer;
import ir.ntnaeem.hottentot.type.*;
import java.util.List;

public class AuthenticateServiceProxy extends AbstractAuthenticateService implements Proxy {
	
  private String host;
  private int port;

  public AuthenticateServiceProxy(String host, int port) {
    this.host = host;
    this.port = port;
  }
  public Token authenticate(Credential credential) { 
    //serialize credential
    byte[] serializedCredential = credential.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(1500029818L);
    request.setMethodId(3526193676L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedCredential.length);
    arg0.setData(serializedCredential);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    //calulate credentialDataLength
    int credentialDataLength= serializedCredential.length;
    int credentialDataLengthByteArrayLength = 1;
    if (credentialDataLength >= 0x80) {
      if (credentialDataLength <= 0xff) {
        //ex 0x81 0xff
        credentialDataLengthByteArrayLength = 2;
      } else if (credentialDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        credentialDataLengthByteArrayLength = 3;
      } else if (credentialDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        credentialDataLengthByteArrayLength = 4;
      }
    }
    dataLength += credentialDataLength + credentialDataLengthByteArrayLength;
    //arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    //connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    //serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    //send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    //read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    //close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize Tokenpart from response
    Token token= null;
    if (response.getStatusCode() == -1) {
      //TODO
    }
    token= new Token();
    token.deserialize(response.getData());
    return token;
  }
  public String f() { 

    //make request
    Request request = new Request();
    request.setServiceId(1500029818L);
    request.setMethodId(2236480184L);
    request.setArgumentCount((byte) 0);
    request.setType(Request.RequestType.InvokeStateless);
    int dataLength = 0;
    //calculate data length for every argument
    //arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    //connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    //serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    //send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    //read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    //close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize stringpart from response
    if (response.getStatusCode() == -1) {
      //TODO
    }
    _String ret = new _String();
    ret.deserialize(response.getData());
    return ret.getValue();
  }
  public int g() { 

    //make request
    Request request = new Request();
    request.setServiceId(1500029818L);
    request.setMethodId(854395736L);
    request.setArgumentCount((byte) 0);
    request.setType(Request.RequestType.InvokeStateless);
    int dataLength = 0;
    //calculate data length for every argument
    //arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    //connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    //serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    //send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    //read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    //close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize int32part from response
    if (response.getStatusCode() == -1) {
      //TODO
    }
    _Int32 ret = new _Int32();
    ret.deserialize(response.getData());
    return ret.getValue();
  }
  public byte[] h() { 

    //make request
    Request request = new Request();
    request.setServiceId(1500029818L);
    request.setMethodId(1177878616L);
    request.setArgumentCount((byte) 0);
    request.setType(Request.RequestType.InvokeStateless);
    int dataLength = 0;
    //calculate data length for every argument
    //arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    //connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    //serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    //send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    //read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    //close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize datapart from response
    if (response.getStatusCode() == -1) {
      //TODO
    }
    _Data ret = new _Data();
    ret.deserialize(response.getData());
    return ret.getValue();
  }

  public void destroy() {
    //TODO
  }
}
