/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package naeem.hottentot.examples.auth.hotgen;

import ir.ntnaeem.hottentot.runtime.Service;
import java.util.List;

public interface AuthenticateService extends Service {
  Token authenticate(Credential credential);
  String f();
  int g();
  byte[] h();

}
