/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 01:22:28
 * Name: .cc
 * Description:
 *   This file contains implementation of  class.
 ******************************************************************/

#include <iostream>
#include <string.h>

#include <naeem/hottentot/runtime/hot_ptr.h>

#include ".h"



  ::(const  &other) {
  }
  ::( *other) {
  }
  unsigned char *
  ::Serialize(uint32_t *length_ptr) {
    uint32_t totalLength = 0;
    unsigned char *data = new unsigned char[totalLength];
    uint32_t c = 0;
    if (c != totalLength) {
      std::cout << "Struct Serialization: Inconsistency in length of serialized byte array." << std::endl;
      exit(1);
    };
    if (length_ptr) {
      *length_ptr = totalLength;
    }
    return data;
  }
  void
  ::Deserialize(unsigned char *data, uint32_t length) {
    uint32_t c = 0, elength = 0;
    if (c != length) {
      std::cout << "Struct Deserialization: Inconsistency in length of deserialized byte array." << std::endl;
      exit(1);
    };
  }
