/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 01:22:28
 * Name: .h
 * Description:
 *   This file contains definition of  class.
 ***************************************************************/

#ifndef ____H_
#define ____H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>

#include "enums.h"



  class  : public ::naeem::hottentot::runtime::Serializable {
  public:
    () {}
    (const  &);
    ( *);
    virtual ~() {}
  public:
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
  };


#endif