/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 02:12:01
 * Name: enums.h
 * Description:
 *   This file contains all enumerations from all modules.
 ******************************************************************/

#ifndef _IR_NTNAEEM_SERVICES_ORG_APACHE_TESTS__ENUMS_H_
#define _IR_NTNAEEM_SERVICES_ORG_APACHE_TESTS__ENUMS_H_

namespace ir {
namespace ntnaeem {
namespace services {
  enum GenderType {
    kGenderType_Male = 1,
    kGenderType_Female = 2
  };
  enum SampleEnumType {
    kSampleEnumType_None = 0,
    kSampleEnumType_Sample_Item_With_Underscore = 1
  };
} // END OF NAMESPACE services
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE irnamespace org {
namespace apache {
namespace tests {
} // END OF NAMESPACE tests
} // END OF NAMESPACE apache
} // END OF NAMESPACE org

#endif