/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 10-02-2016 04:04:57
 * Name: enums.h
 * Description:
 *   This file contains all enumerations.
 ******************************************************************/

#ifndef _ORG_APACHE_TESTS__ENUMS_H_
#define _ORG_APACHE_TESTS__ENUMS_H_

namespace org {
namespace apache {
namespace tests {
[[[ENUMS]]]
} // END OF NAMESPACE tests
} // END OF NAMESPACE apache
} // END OF NAMESPACE org

#endif