/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 16-01-2016 01:33:10
 * Name: echo_service_client.h
 * Description:
 *   This file contains a sample client.
 ******************************************************************/

#include <iostream>

#include <naeem/hottentot/runtime/configuration.h>
#include <naeem/hottentot/runtime/logger.h>
#include <naeem/hottentot/runtime/proxy/proxy_runtime.h>

#include "../gen/request_message.h"
#include "../gen/response_message.h"
#include "../gen/echo_service.h"
#include "../gen/proxy/echo_service_proxy_builder.h"


int 
main(int argc, char **argv) {
  try {
    ::naeem::hottentot::runtime::Logger::Init();  
    ::naeem::hottentot::runtime::proxy::ProxyRuntime::Init(argc, argv);
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "Proxy runtime is initialized." << std::endl;
    }
    ::ir::ntnaeem::hottentot::examples::echoer::EchoService *proxy = 
        ::ir::ntnaeem::hottentot::examples::echoer::proxy::EchoServiceProxyBuilder::Create("127.0.0.1", 2000);
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "Proxy object is created." << std::endl;
    }
    ::naeem::hottentot::runtime::types::Utf8String name("Kamran");
    ::ir::ntnaeem::hottentot::examples::echoer::RequestMessage req;
    req.SetName(name);
    ::ir::ntnaeem::hottentot::examples::echoer::ResponseMessage resp;
    proxy->EchoMessage(req, resp);
    unsigned char *data = resp.GetMessage().Serialize(NULL);
    std::cout << data << std::endl;
    delete [] data;
    ::ir::ntnaeem::hottentot::examples::echoer::proxy::EchoServiceProxyBuilder::Destroy(proxy);
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "Proxy object is destroyed." << std::endl;
    }
  } catch (...) {
    ::naeem::hottentot::runtime::Logger::GetOut() << "Error." << std::endl;
    return 1;
  }
  return 0;
}
