/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.hotgen.client;

import ir.ntnaeem.hottentot.examples.listtest.hotgen.ManagementService;
import ir.ntnaeem.hottentot.examples.listtest.hotgen.ManagementServiceProxyBuilder;
import ir.ntnaeem.hottentot.examples.listtest.hotgen.ReportingService;
import ir.ntnaeem.hottentot.examples.listtest.hotgen.ReportingServiceProxyBuilder;
import ir.ntnaeem.hottentot.examples.listtest.hotgen.MonitoringService;
import ir.ntnaeem.hottentot.examples.listtest.hotgen.MonitoringServiceProxyBuilder;

import java.io.IOException;

public class Main {
  public static void main(String[] args) throws IOException {
    ir.ntnaeem.hottentot.runtime.config.Config.setMainArgs(args);
    final ManagementService managementProxy = ManagementServiceProxyBuilder.create("127.0.0.1", 8080);
    final ReportingService reportingProxy = ReportingServiceProxyBuilder.create("127.0.0.1", 8080);
    final MonitoringService monitoringProxy = MonitoringServiceProxyBuilder.create("127.0.0.1", 8080);

    //use server methods on proxies
  }
}