/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 01-02-2016 01:45:06
 * Name: echo_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <naeem/hottentot/runtime/request.h>
#include <naeem/hottentot/runtime/response.h>

#include "echo_service_request_handler.h"
#include "abstract_echo_service.h"
#include "../echo_service.h"
#include "../echo_request.h"
#include "../echo_response.h"


namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace win32 {
namespace echo {
namespace service {
  void 
  EchoServiceRequestHandler::HandleRequest(::naeem::hottentot::runtime::Request &request, ::naeem::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 165906122) {
      ::ir::ntnaeem::hottentot::examples::win32::echo::service::AbstractEchoService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::hottentot::examples::win32::echo::service::AbstractEchoService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::ir::ntnaeem::hottentot::examples::win32::echo::EchoRequest req;
      req.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::ir::ntnaeem::hottentot::examples::win32::echo::EchoResponse result;
      serviceObject->DoEcho(req, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE echo
} // END OF NAMESPACE win32
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir