/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 01-02-2016 01:45:06
 * Name: echo_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "echo_service_proxy_builder.h"
#include "echo_service_proxy.h"


namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace win32 {
namespace echo {
namespace proxy {
  EchoService*
  EchoServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new EchoServiceProxy(host, port);
  }
  void
  EchoServiceProxyBuilder::Destroy(EchoService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE echo
} // END OF NAMESPACE win32
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir