/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.hotgen;

import ir.ntnaeem.hottentot.runtime.RequestHandler;

public abstract class AbstractListTestService implements ListTestService {	
  public RequestHandler makeRequestHandler() {
    return new ListTestRequestHandler(this);
  }
  public long getServiceId() {
    return 304603072L;
  }
}
