/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.hotgen;

import ir.ntnaeem.hottentot.runtime.RequestHandler;

public abstract class AbstractReportingService implements ReportingService {	
  public RequestHandler makeRequestHandler() {
    return new ReportingRequestHandler(this);
  }
  public long getServiceId() {
    return 1526418773L;
  }
}
