/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   This file contains definition of an abstract service class.
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.hotgen;

import ir.ntnaeem.hottentot.serializerHelper.PDTSerializer;
import ir.ntnaeem.hottentot.serializerHelper.PDTDeserializer;
import ir.ntnaeem.hottentot.serializerHelper.ByteArrayToInteger;
import java.util.List;
import java.util.ArrayList;

public class Crawler {
  private long id;
  private byte type;
  private String name = "";
  private String ip = "";
  private short port;
  private String startURL = "";
  private List<String> domainList = new ArrayList<String>();
  public void setId(long id) {
    this.id = id;
  }
  public long getId() {
    return id;
  }
  public void setType(byte type) {
    this.type = type;
  }
  public byte getType() {
    return type;
  }
  public void setName(String name) {
    this.name = name;
  }
  public String getName() {
    return name;
  }
  public void setIp(String ip) {
    this.ip = ip;
  }
  public String getIp() {
    return ip;
  }
  public void setPort(short port) {
    this.port = port;
  }
  public short getPort() {
    return port;
  }
  public void setStartURL(String startURL) {
    this.startURL = startURL;
  }
  public String getStartURL() {
    return startURL;
  }
  public void setDomainList(List<String> domainList) {
    this.domainList = domainList;
  }
  public List<String> getDomainList() {
    return domainList;
  }
  @Override 
  public String toString() { 
    return "Crawler{" + 
      "id = '" + id + '\'' + 
      ",type = '" + type + '\'' + 
      ",name = '" + name + '\'' + 
      ",ip = '" + ip + '\'' + 
      ",port = '" + port + '\'' + 
      ",startURL = '" + startURL + '\'' + 
      ",domainList = '" + domainList + '\'' + 
      "}"; 
  }
	
  public byte[] serialize() {
    byte[] serializedId = PDTSerializer.getInt64(id);
    byte[] serializedType = PDTSerializer.getInt8(type);
    byte[] serializedName = PDTSerializer.getString(name);
    byte[] serializedIp = PDTSerializer.getString(ip);
    byte[] serializedPort = PDTSerializer.getInt16(port);
    byte[] serializedStartURL = PDTSerializer.getString(startURL);
    SerializableStringList serializableStringList7 = new SerializableStringList();
    serializableStringList7.setStringList(domainList);
    byte[] serializedDomainList  = serializableStringList7.serializeWithLength();
    byte[] output = new byte[serializedId.length + serializedType.length + serializedName.length + serializedIp.length + serializedPort.length + serializedStartURL.length + serializedDomainList.length];
    int counter = 0;
    //use a loop for every property
    for (int i = 0; i < serializedId.length; i++) {
      output[counter++] = serializedId[i];
    }
    for (int i = 0; i < serializedType.length; i++) {
      output[counter++] = serializedType[i];
    }
    for (int i = 0; i < serializedName.length; i++) {
      output[counter++] = serializedName[i];
    }
    for (int i = 0; i < serializedIp.length; i++) {
      output[counter++] = serializedIp[i];
    }
    for (int i = 0; i < serializedPort.length; i++) {
      output[counter++] = serializedPort[i];
    }
    for (int i = 0; i < serializedStartURL.length; i++) {
      output[counter++] = serializedStartURL[i];
    }
    for (int i = 0; i < serializedDomainList.length; i++) {
      output[counter++] = serializedDomainList[i];
    }
    return output;
  }
    
  public void deserialize(byte[] serializedByteArray) {
    if(serializedByteArray.length != 0){
      int counter = 0;
      int dataLength = 0;
      int numbersOfBytesForDataLength;
      //do for every property
    //id : long
    byte[] idByteArray = new byte[8];
    for(int i = 0 ; i < 8 ; i++){
      idByteArray[i] = serializedByteArray[counter++];
    }
    setId(PDTDeserializer.getInt64(idByteArray));
    //type : byte
    byte[] typeByteArray = new byte[1];
    for(int i = 0 ; i < 1 ; i++){
      typeByteArray[i] = serializedByteArray[counter++];
    }
    setType(PDTDeserializer.getInt8(typeByteArray));
    //name : String
    dataLength = 0;
    if(( serializedByteArray[counter] & 0x80) == 0 ) {
      dataLength = serializedByteArray[counter++];
    }else{
      numbersOfBytesForDataLength = serializedByteArray[counter++] & 0x0f;
      byte[] serializedByteArrayLength = new byte[numbersOfBytesForDataLength];
      for(byte i = 0 ; i < numbersOfBytesForDataLength ; i++){
        serializedByteArrayLength[i] = serializedByteArray[counter++];
      }
      dataLength = ByteArrayToInteger.getInt(serializedByteArrayLength);
    }
    byte[] nameByteArray = new byte[dataLength];
    System.arraycopy(serializedByteArray,counter,nameByteArray,0,dataLength);
    counter += dataLength;
    setName(PDTDeserializer.getString(nameByteArray));
    //ip : String
    dataLength = 0;
    if(( serializedByteArray[counter] & 0x80) == 0 ) {
      dataLength = serializedByteArray[counter++];
    }else{
      numbersOfBytesForDataLength = serializedByteArray[counter++] & 0x0f;
      byte[] serializedByteArrayLength = new byte[numbersOfBytesForDataLength];
      for(byte i = 0 ; i < numbersOfBytesForDataLength ; i++){
        serializedByteArrayLength[i] = serializedByteArray[counter++];
      }
      dataLength = ByteArrayToInteger.getInt(serializedByteArrayLength);
    }
    byte[] ipByteArray = new byte[dataLength];
    System.arraycopy(serializedByteArray,counter,ipByteArray,0,dataLength);
    counter += dataLength;
    setIp(PDTDeserializer.getString(ipByteArray));
    //port : short
    byte[] portByteArray = new byte[2];
    for(int i = 0 ; i < 2 ; i++){
      portByteArray[i] = serializedByteArray[counter++];
    }
    setPort(PDTDeserializer.getInt16(portByteArray));
    //startURL : String
    dataLength = 0;
    if(( serializedByteArray[counter] & 0x80) == 0 ) {
      dataLength = serializedByteArray[counter++];
    }else{
      numbersOfBytesForDataLength = serializedByteArray[counter++] & 0x0f;
      byte[] serializedByteArrayLength = new byte[numbersOfBytesForDataLength];
      for(byte i = 0 ; i < numbersOfBytesForDataLength ; i++){
        serializedByteArrayLength[i] = serializedByteArray[counter++];
      }
      dataLength = ByteArrayToInteger.getInt(serializedByteArrayLength);
    }
    byte[] startURLByteArray = new byte[dataLength];
    System.arraycopy(serializedByteArray,counter,startURLByteArray,0,dataLength);
    counter += dataLength;
    setStartURL(PDTDeserializer.getString(startURLByteArray));
    //domainList : List<String>
    dataLength = 0;
    if(( serializedByteArray[counter] & 0x80) == 0 ) {
      dataLength = serializedByteArray[counter++];
    }else{
      numbersOfBytesForDataLength = serializedByteArray[counter++] & 0x0f;
      byte[] serializedByteArrayLength = new byte[numbersOfBytesForDataLength];
      for(byte i = 0 ; i < numbersOfBytesForDataLength ; i++){
        serializedByteArrayLength[i] = serializedByteArray[counter++];
      }
      dataLength = ByteArrayToInteger.getInt(serializedByteArrayLength);
    }
    byte[] domainListByteArray = new byte[dataLength];
    System.arraycopy(serializedByteArray,counter,domainListByteArray,0,dataLength);
    counter += dataLength;
    SerializableStringList serializableStringList1 = new SerializableStringList();
    serializableStringList1.deserialize(domainListByteArray);
    setDomainList(serializableStringList1.getStringList());

    }
  }
}
