/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.hotgen;

import ir.ntnaeem.hottentot.runtime.Argument;
import ir.ntnaeem.hottentot.runtime.Proxy;
import ir.ntnaeem.hottentot.runtime.Request;
import ir.ntnaeem.hottentot.runtime.Response;
import ir.ntnaeem.hottentot.runtime.TcpClient;
import ir.ntnaeem.hottentot.runtime.exception.HottentotRuntimeException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientConnectException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientReadException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientWriteException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientCloseException;
import ir.ntnaeem.hottentot.runtime.factory.ProtocolFactory;
import ir.ntnaeem.hottentot.runtime.factory.TcpClientFactory;
import ir.ntnaeem.hottentot.runtime.protocol.Protocol;
import ir.ntnaeem.hottentot.serializerHelper.PDTSerializer;
import ir.ntnaeem.hottentot.serializerHelper.PDTDeserializer;
import ir.ntnaeem.hottentot.type.*;
import java.util.List;

public class MonitoringServiceProxy extends AbstractMonitoringService implements Proxy {
	
  private String host;
  private int port;

  public MonitoringServiceProxy(String host, int port) {
    this.host = host;
    this.port = port;
  }
  public void registerCrawlerId(long crawlerId) { 
    //serialize crawlerId
    _Int64 crawlerIdWrapper = new _Int64(crawlerId);
    byte[] serializedCrawlerId = crawlerIdWrapper.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(2465892066L);
    request.setMethodId(2792721284L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedCrawlerId.length);
    arg0.setData(serializedCrawlerId);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    //calulate crawlerIdDataLength
    int crawlerIdDataLength= serializedCrawlerId.length;
    int crawlerIdDataLengthByteArrayLength = 1;
    if (crawlerIdDataLength >= 0x80) {
      if (crawlerIdDataLength <= 0xff) {
        //ex 0x81 0xff
        crawlerIdDataLengthByteArrayLength = 2;
      } else if (crawlerIdDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        crawlerIdDataLengthByteArrayLength = 3;
      } else if (crawlerIdDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        crawlerIdDataLengthByteArrayLength = 4;
      }
    }
    dataLength += crawlerIdDataLength + crawlerIdDataLengthByteArrayLength;
    //arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    //connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    //serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    //send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
  }
  public void unregisterCrawlerId(long crawlerId) { 
    //serialize crawlerId
    _Int64 crawlerIdWrapper = new _Int64(crawlerId);
    byte[] serializedCrawlerId = crawlerIdWrapper.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(2465892066L);
    request.setMethodId(1585613181L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedCrawlerId.length);
    arg0.setData(serializedCrawlerId);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    //calulate crawlerIdDataLength
    int crawlerIdDataLength= serializedCrawlerId.length;
    int crawlerIdDataLengthByteArrayLength = 1;
    if (crawlerIdDataLength >= 0x80) {
      if (crawlerIdDataLength <= 0xff) {
        //ex 0x81 0xff
        crawlerIdDataLengthByteArrayLength = 2;
      } else if (crawlerIdDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        crawlerIdDataLengthByteArrayLength = 3;
      } else if (crawlerIdDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        crawlerIdDataLengthByteArrayLength = 4;
      }
    }
    dataLength += crawlerIdDataLength + crawlerIdDataLengthByteArrayLength;
    //arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    //connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    //serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    //send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
  }
  public List<MonitoredCrawlerInfo> getMonitoredCrawlersInfo(List<Long> crawlerIdlist) { 
    //serialize crawlerIdlist
    SerializableUint64List serializableUint64List = new SerializableUint64List();
serializableUint64List.setUint64List(crawlerIdlist);
byte[] serializedCrawlerIdlist = serializableUint64List.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(2465892066L);
    request.setMethodId(2322248127L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedCrawlerIdlist.length);
    arg0.setData(serializedCrawlerIdlist);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    //calulate crawlerIdlistDataLength
    int crawlerIdlistDataLength= serializedCrawlerIdlist.length;
    int crawlerIdlistDataLengthByteArrayLength = 1;
    if (crawlerIdlistDataLength >= 0x80) {
      if (crawlerIdlistDataLength <= 0xff) {
        //ex 0x81 0xff
        crawlerIdlistDataLengthByteArrayLength = 2;
      } else if (crawlerIdlistDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        crawlerIdlistDataLengthByteArrayLength = 3;
      } else if (crawlerIdlistDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        crawlerIdlistDataLengthByteArrayLength = 4;
      }
    }
    dataLength += crawlerIdlistDataLength + crawlerIdlistDataLengthByteArrayLength;
    //arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    //connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    //serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    //send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    //read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    //close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize list<MonitoredCrawlerInfo>part from response
    SerializableMonitoredCrawlerInfoList serializableMonitoredCrawlerInfoList = null;
    if (response.getStatusCode() == -1) {
      //TODO
    }
    serializableMonitoredCrawlerInfoList = new SerializableMonitoredCrawlerInfoList();
    serializableMonitoredCrawlerInfoList.deserialize(response.getData());
    return serializableMonitoredCrawlerInfoList.getMonitoredCrawlerInfoList();
  }

  public void destroy() {
    //TODO
  }
}
