/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.hotgen;

import ir.ntnaeem.hottentot.runtime.Argument;
import ir.ntnaeem.hottentot.runtime.Request;
import ir.ntnaeem.hottentot.runtime.RequestHandler;
import ir.ntnaeem.hottentot.runtime.Response;
import ir.ntnaeem.hottentot.runtime.Service;
import ir.ntnaeem.hottentot.runtime.config.Config;
import ir.ntnaeem.hottentot.runtime.exception.MethodNotSupportException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientConnectException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientReadException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientWriteException;
import ir.ntnaeem.hottentot.serializerHelper.PDTDeserializer;
import ir.ntnaeem.hottentot.serializerHelper.PDTSerializer;
import java.util.List;

public class MonitoringRequestHandler extends RequestHandler {
  public MonitoringRequestHandler(Service service) {
    super(service);
  }
  @Override
  public Response handleRequest(Request request) throws TcpClientWriteException, TcpClientReadException, TcpClientConnectException {
    long methodId = request.getMethodId();
    MonitoringService monitoringImpl = (AbstractMonitoringService) service;
    if(methodId == 2792721284L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedCrawlerId = arg0.getData();
      long crawlerId = PDTDeserializer.getUint64(serializedCrawlerId);
      Response response = new Response();
      monitoringImpl.registerCrawlerId(crawlerId);
      response.setStatusCode((byte) 0);
      response.setData(new byte[]{0});
      response.setLength(0);
      return response;
    }
    if(methodId == 1585613181L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedCrawlerId = arg0.getData();
      long crawlerId = PDTDeserializer.getUint64(serializedCrawlerId);
      Response response = new Response();
      monitoringImpl.unregisterCrawlerId(crawlerId);
      response.setStatusCode((byte) 0);
      response.setData(new byte[]{0});
      response.setLength(0);
      return response;
    }
    if(methodId == 2322248127L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedCrawlerIdlist = arg0.getData();
      SerializableUint64List serializableUint64List = new SerializableUint64List();
      serializableUint64List.deserialize( serializedCrawlerIdlist);
      List<Long> crawlerIdlist = serializableUint64List.getUint64List();
      SerializableMonitoredCrawlerInfoList serializableMonitoredCrawlerInfoList = new SerializableMonitoredCrawlerInfoList();
      Response response = new Response();
      List<MonitoredCrawlerInfo> monitoredcrawlerinfoList = monitoringImpl.getMonitoredCrawlersInfo(crawlerIdlist);
      byte[] serializedMonitoredCrawlerInfoList;
      if(monitoredcrawlerinfoList == null){
        serializedMonitoredCrawlerInfoList  = new byte[0];
      }else{
        serializableMonitoredCrawlerInfoList.setMonitoredCrawlerInfoList(monitoredcrawlerinfoList);
        serializedMonitoredCrawlerInfoList = serializableMonitoredCrawlerInfoList.serialize();
      }
      response.setStatusCode((byte) 0);
      response.setData(serializedMonitoredCrawlerInfoList);
      response.setLength(serializedMonitoredCrawlerInfoList.length + 1);
      return response;
    }

    Response response = new Response();
    response.setStatusCode((byte) 255);
    response.setData(new byte[]{0});
    response.setLength(2);
    if(Config.isVerboseMode){
      System.out.println("WARN : method id is incorrect");
    }
    return response;
  }
}
