/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package ir.ntnaeem.hottentot.examples.listtest.hotgen;

import ir.ntnaeem.hottentot.runtime.Service;
import java.util.List;

public interface MonitoringService extends Service {
  void registerCrawlerId(long crawlerId);
  void unregisterCrawlerId(long crawlerId);
  List<MonitoredCrawlerInfo> getMonitoredCrawlersInfo(List<Long> crawlerIdlist);

}
