/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 30-01-2016 08:21:47
 * Name: test_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <naeem/hottentot/runtime/request.h>
#include <naeem/hottentot/runtime/response.h>

#include "test_service_request_handler.h"
#include "abstract_test_service.h"
#include "../test_service.h"
#include "../token.h"
#include "../credential.h"
#include "../data_wrapper.h"
#include "../string_wrapper.h"
#include "../sample_struct.h"
#include "../result.h"


namespace hotgen {
namespace service {
  void 
  TestServiceRequestHandler::HandleRequest(::naeem::hottentot::runtime::Request &request, ::naeem::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 3860892363) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::hotgen::Credential credential;
      credential.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::types::List< ::hotgen::Token> result;
      serviceObject->Auth(credential, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 2066849401) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::types::List< ::hotgen::DataWrapper> result;
      serviceObject->Test(result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 2719924681) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::types::List< ::hotgen::StringWrapper> result;
      serviceObject->Test2(result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 3413469625) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      /*
       * Calling service method
       */
      ::hotgen::StringWrapper result;
      serviceObject->Test3(result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 3943078220) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      /*
       * Calling service method
       */
      ::hotgen::DataWrapper result;
      serviceObject->Test4(result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 3893264993) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::List< ::hotgen::StringWrapper> inputList;
      inputList.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::hotgen::DataWrapper result;
      serviceObject->Test5(inputList, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 3743195557) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::List< ::hotgen::DataWrapper> inputs;
      inputs.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::hotgen::DataWrapper result;
      serviceObject->Test6(inputs, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 944580077) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      /*
       * Calling service method
       */
      ::hotgen::SampleStruct result;
      serviceObject->Test7(result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 3742699770) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::hotgen::StringWrapper str;
      str.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::hotgen::StringWrapper result;
      serviceObject->Test8(str, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 539315280) {
      ::hotgen::service::AbstractTestService *serviceObject = 
        dynamic_cast< ::hotgen::service::AbstractTestService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::hotgen::SampleStruct sample;
      sample.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::hotgen::Result result;
      serviceObject->Test9(sample, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE hotgen