/***********************************************************************
 * Generated by Hottentot CC Generator
 * Date: 30-01-2016 08:21:47
 * Name: test_service_request_handler.h
 * Description:
 *   This file contains definition of service's request handler class.
 ***********************************************************************/

#ifndef _HOTGEN__SERVICE__TEST_SERVICE_REQUEST_HANDLER_H_
#define _HOTGEN__SERVICE__TEST_SERVICE_REQUEST_HANDLER_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/service/request_handler.h>


namespace hotgen {
namespace service {
  class TestServiceRequestHandler : public ::naeem::hottentot::runtime::service::RequestHandler {
  public:
    TestServiceRequestHandler(::naeem::hottentot::runtime::service::Service *service)
      : ::naeem::hottentot::runtime::service::RequestHandler(service) {
    }
    virtual ~TestServiceRequestHandler() {}
  public:
    virtual void HandleRequest(::naeem::hottentot::runtime::Request &   /* Request object */, ::naeem::hottentot::runtime::Response &  /* Response object */);
  };
} // END OF NAMESPACE service
} // END OF NAMESPACE hotgen

#endif