/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 02-05-2016 05:11:23
 * Name: calculator_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <org/labcrypto/hottentot/runtime/request.h>
#include <org/labcrypto/hottentot/runtime/response.h>

#include "calculator_service_request_handler.h"
#include "abstract_calculator_service.h"
#include "calculator_service.h"



namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace calc {
namespace service {
  void 
  CalculatorServiceRequestHandler::HandleRequest(::org::labcrypto::hottentot::runtime::Request &request, ::org::labcrypto::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 721739713) {
      ::ir::ntnaeem::hottentot::examples::calc::service::AbstractCalculatorService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::hottentot::examples::calc::service::AbstractCalculatorService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::org::labcrypto::hottentot::UInt16 a;
      a.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      ::org::labcrypto::hottentot::UInt16 b;
      b.Deserialize(request.GetArgumentData(1), request.GetArgumentLength(1));
      /*
       * Calling service method
       */
      ::org::labcrypto::hottentot::runtime::service::HotContext hotContext;
      
      ::org::labcrypto::hottentot::UInt16 result;
      try {
        serviceObject->Add(a, b, result, hotContext);
      } catch (std::exception &e) {
        hotContext.SetFaultyResponse(e.what(), 50);
      } catch (...) {
        hotContext.SetFaultyResponse("Unknown server side exception.", 51);
      }
      /*
       * Serializiation of returned object
       */
      unsigned char *serializedData = 0;
      uint32_t serializedDataLength = 0;
      if (hotContext.GetResponseStatusCode() == 0) {
        serializedData = result.Serialize(&serializedDataLength);
      } else {
        ::org::labcrypto::hottentot::Utf8String faultMessage(hotContext.GetFaultMessage());
        serializedData = faultMessage.Serialize(&serializedDataLength);
      }
      response.SetStatusCode(hotContext.GetResponseStatusCode());
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 605561134) {
      ::ir::ntnaeem::hottentot::examples::calc::service::AbstractCalculatorService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::hottentot::examples::calc::service::AbstractCalculatorService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::org::labcrypto::hottentot::Int16 a;
      a.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      ::org::labcrypto::hottentot::Int16 b;
      b.Deserialize(request.GetArgumentData(1), request.GetArgumentLength(1));
      /*
       * Calling service method
       */
      ::org::labcrypto::hottentot::runtime::service::HotContext hotContext;
      
      ::org::labcrypto::hottentot::Int16 result;
      try {
        serviceObject->Mul(a, b, result, hotContext);
      } catch (std::exception &e) {
        hotContext.SetFaultyResponse(e.what(), 50);
      } catch (...) {
        hotContext.SetFaultyResponse("Unknown server side exception.", 51);
      }
      /*
       * Serializiation of returned object
       */
      unsigned char *serializedData = 0;
      uint32_t serializedDataLength = 0;
      if (hotContext.GetResponseStatusCode() == 0) {
        serializedData = result.Serialize(&serializedDataLength);
      } else {
        ::org::labcrypto::hottentot::Utf8String faultMessage(hotContext.GetFaultMessage());
        serializedData = faultMessage.Serialize(&serializedDataLength);
      }
      response.SetStatusCode(hotContext.GetResponseStatusCode());
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE calc
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir