/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.hottentot.examples.listtest;

import org.labcrypto.hottentot.runtime.RequestHandler;


public abstract class AbstractListTestService implements ListTestService {	
  public RequestHandler makeRequestHandler() {
    return new ListTestRequestHandler(this);
  }
  public long getServiceId() {
    return 1870052030L;
  }
}
