/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.hottentot.examples.listtest;

import java.util.*;

import org.labcrypto.hottentot.*;
import org.labcrypto.hottentot.runtime.Argument;
import org.labcrypto.hottentot.runtime.Proxy;
import org.labcrypto.hottentot.runtime.Request;
import org.labcrypto.hottentot.runtime.Response;
import org.labcrypto.hottentot.runtime.TcpClient;
import org.labcrypto.hottentot.runtime.exception.HottentotRuntimeException;
import org.labcrypto.hottentot.runtime.exception.TcpClientConnectException;
import org.labcrypto.hottentot.runtime.exception.TcpClientReadException;
import org.labcrypto.hottentot.runtime.exception.TcpClientWriteException;
import org.labcrypto.hottentot.runtime.exception.TcpClientCloseException;
import org.labcrypto.hottentot.runtime.factory.ProtocolFactory;
import org.labcrypto.hottentot.runtime.factory.TcpClientFactory;
import org.labcrypto.hottentot.runtime.protocol.Protocol;


public class ListTestServiceProxy extends AbstractListTestService implements Proxy {
	
  private String host;
  private int port;

  public ListTestServiceProxy(String host, int port) {
    this.host = host;
    this.port = port;
  }
  public void addNames(List<String> names) { 
    //serialize names
    SerializableStringList serializableStringList = new SerializableStringList();
serializableStringList.setStringList(names);
byte[] serializedNames = serializableStringList.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(1870052030L);
    request.setMethodId(991498108L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedNames.length);
    arg0.setData(serializedNames);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    // calulate namesDataLength
    int namesDataLength= serializedNames.length;
    int namesDataLengthByteArrayLength = 1;
    if (namesDataLength >= 0x80) {
      if (namesDataLength <= 0xff) {
        //ex 0x81 0xff
        namesDataLengthByteArrayLength = 2;
      } else if (namesDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        namesDataLengthByteArrayLength = 3;
      } else if (namesDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        namesDataLengthByteArrayLength = 4;
      }
    }
    dataLength += namesDataLength + namesDataLengthByteArrayLength;
    // arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    // connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    // serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    // send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
  }
  public List<String> getNames() { 

    //make request
    Request request = new Request();
    request.setServiceId(1870052030L);
    request.setMethodId(1775487014L);
    request.setArgumentCount((byte) 0);
    request.setType(Request.RequestType.InvokeStateless);
    int dataLength = 0;
    //calculate data length for every argument
    // arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    // connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    // serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    // send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    // read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    // close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize list<string>part from response
    SerializableStringList serializableStringList = null;
    if (response.getStatusCode() == -1) {
      //TODO
    }
    serializableStringList = new SerializableStringList();
    serializableStringList.deserialize(response.getData());
    return serializableStringList.getStringList();
  }
  public List<MessageBox> getMessages() { 

    //make request
    Request request = new Request();
    request.setServiceId(1870052030L);
    request.setMethodId(1931876033L);
    request.setArgumentCount((byte) 0);
    request.setType(Request.RequestType.InvokeStateless);
    int dataLength = 0;
    //calculate data length for every argument
    // arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    // connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    // serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    // send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    // read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    // close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize list<MessageBox>part from response
    SerializableMessageBoxList serializableMessageBoxList = null;
    if (response.getStatusCode() == -1) {
      //TODO
    }
    serializableMessageBoxList = new SerializableMessageBoxList();
    serializableMessageBoxList.deserialize(response.getData());
    return serializableMessageBoxList.getMessageBoxList();
  }
  public void addMessage(MessageBox message) { 
    //serialize message
    byte[] serializedMessage = message.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(1870052030L);
    request.setMethodId(2566968978L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedMessage.length);
    arg0.setData(serializedMessage);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    // calulate messageDataLength
    int messageDataLength= serializedMessage.length;
    int messageDataLengthByteArrayLength = 1;
    if (messageDataLength >= 0x80) {
      if (messageDataLength <= 0xff) {
        //ex 0x81 0xff
        messageDataLengthByteArrayLength = 2;
      } else if (messageDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        messageDataLengthByteArrayLength = 3;
      } else if (messageDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        messageDataLengthByteArrayLength = 4;
      }
    }
    dataLength += messageDataLength + messageDataLengthByteArrayLength;
    // arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    // connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    // serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    // send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
  }
  public void addShortNumbers(List<Short> numbers) { 
    //serialize numbers
    SerializableUint16List serializableUint16List = new SerializableUint16List();
serializableUint16List.setUint16List(numbers);
byte[] serializedNumbers = serializableUint16List.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(1870052030L);
    request.setMethodId(2756556211L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedNumbers.length);
    arg0.setData(serializedNumbers);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    // calulate numbersDataLength
    int numbersDataLength= serializedNumbers.length;
    int numbersDataLengthByteArrayLength = 1;
    if (numbersDataLength >= 0x80) {
      if (numbersDataLength <= 0xff) {
        //ex 0x81 0xff
        numbersDataLengthByteArrayLength = 2;
      } else if (numbersDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        numbersDataLengthByteArrayLength = 3;
      } else if (numbersDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        numbersDataLengthByteArrayLength = 4;
      }
    }
    dataLength += numbersDataLength + numbersDataLengthByteArrayLength;
    // arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    // connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    // serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    // send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
  }
  public void addByteNumbers(List<Byte> numbers) { 
    //serialize numbers
    SerializableUint8List serializableUint8List = new SerializableUint8List();
serializableUint8List.setUint8List(numbers);
byte[] serializedNumbers = serializableUint8List.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(1870052030L);
    request.setMethodId(3449511521L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedNumbers.length);
    arg0.setData(serializedNumbers);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    // calulate numbersDataLength
    int numbersDataLength= serializedNumbers.length;
    int numbersDataLengthByteArrayLength = 1;
    if (numbersDataLength >= 0x80) {
      if (numbersDataLength <= 0xff) {
        //ex 0x81 0xff
        numbersDataLengthByteArrayLength = 2;
      } else if (numbersDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        numbersDataLengthByteArrayLength = 3;
      } else if (numbersDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        numbersDataLengthByteArrayLength = 4;
      }
    }
    dataLength += numbersDataLength + numbersDataLengthByteArrayLength;
    // arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    // connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    // serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    // send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
  }

  public void destroy() {
    //TODO
  }
}
