/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.hottentot.examples.listtest;

import java.io.IOException;


public class SampleClient {
  public static void main(String[] args) {
    try{
      org.labcrypto.hottentot.runtime.config.Config.setMainArgs(args);
      final ListTestService listtestProxy = ListTestServiceProxyBuilder.create("10.1.2.3", 6000);
      listtestProxy.getNames();
    }catch (Exception e){
      e.printStackTrace();
      System.out.println("aaa");
    }
  }
}