/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package client;

import example.generated.hotgen.*;

import java.io.IOException;

public class Main {
  public static void main(String[] args) throws IOException {
    ir.ntnaeem.hottentot.runtime.config.Config.setMainArgs(args);
    final AuthenticationService proxy = AuthenticationServiceProxyBuilder.create("127.0.0.1", 2000);
    final SecondService secondServiceProxy = SecondServiceProxyBuilder.create("127.0.0.1", 2000);
    final SecondService secondServiceProxy2 = SecondServiceProxyBuilder.create("20.30.40.52", 3000);
    //byte a = proxy.test9("a", true, (short) 10, new byte[]{1});
    proxy.test13(GenderType.Female);
    int ret = secondServiceProxy.f();
    int ret2 = secondServiceProxy2.f();
    System.out.println("ret : " + ret);
    System.out.println("ret : " + ret2);
  }
}