/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package client;

import example.generated.AuthenticationService;
import example.generated.AuthenticationServiceProxyBuilder;

import java.io.IOException;

public class Main {
  public static void main(String[] args) throws IOException {
    ir.ntnaeem.hottentot.runtime.config.Config.setMainArgs(args);
    final AuthenticationService proxy = AuthenticationServiceProxyBuilder.create("127.0.0.1", 2000);
    byte a = proxy.test9("a", true, (short) 10, new byte[]{1});
    System.out.println(a);

  }
}