/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.hottentot.examples.listtest.hotgen_correct;

public class ListTestServiceProxyBuilder {

  public static ListTestService create(String host, int port) {
    return new ListTestServiceProxy(host,port);
  }

  public static void destroy() {
    //TODO
  }
}
