/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 24-08-2016 11:09:22
 * Name: big_file_transfer_service_proxy_builder.h
 * Description:
 *   This file contains definition of the proxy builder class.
 ******************************************************************/

#ifndef _ORG_LABCRYPTO_HOTTENTOT_EXAMPLES_BIGFILETRANSFER__PROXY__BIG_FILE_TRANSFER_SERVICE_PROXY_BUILDER_H_
#define _ORG_LABCRYPTO_HOTTENTOT_EXAMPLES_BIGFILETRANSFER__PROXY__BIG_FILE_TRANSFER_SERVICE_PROXY_BUILDER_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>


namespace org {
namespace labcrypto {
namespace hottentot {
namespace examples {
namespace bigfiletransfer {
namespace proxy {
class BigFileTransferService;
  class BigFileTransferServiceProxyBuilder {
  public:
    static BigFileTransferService* Create(std::string /* host */, uint32_t /* port */);
    static void Destroy(BigFileTransferService *);
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE bigfiletransfer
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org

#endif