/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 01:32:49
 * Name: authentication_service.h
 * Description:
 *   This file contains definition of an abstract service class.
 ******************************************************************/

#ifndef _EXAMPLE_GENERATED_ABC_XYZ__SERVICE__ABSTRACT_AUTHENTICATION_SERVICE_H_
#define _EXAMPLE_GENERATED_ABC_XYZ__SERVICE__ABSTRACT_AUTHENTICATION_SERVICE_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/service/service.h>

#include "../token.h"
#include "../credential.h"
#include "../date_time.h"

#include "authentication_service.h"
#include "authentication_service_request_handler.h"


namespace example {
namespace generated {
namespace abc {
namespace xyz {
namespace service {
  class AbstractAuthenticationService : public AuthenticationService, public ::naeem::hottentot::runtime::service::Service {
  public:
    AbstractAuthenticationService() {}
    virtual ~AbstractAuthenticationService() {}
  public:
    inline virtual uint32_t GetServiceId() const {
      return 3709056755;
    }
  protected:
    inline virtual ::naeem::hottentot::runtime::service::RequestHandler* MakeRequestHandler() {
      return new AuthenticationServiceRequestHandler(this);
    }
  };
} // END OF NAMESPACE service
} // END OF NAMESPACE xyz
} // END OF NAMESPACE abc
} // END OF NAMESPACE generated
} // END OF NAMESPACE example

#endif