/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 10-02-2016 03:18:32
 * Name: apache_license_manager_service.h
 * Description:
 *   This file contains definition of an abstract service class.
 ******************************************************************/

#ifndef _ORG_APACHE_TESTS__SERVICE__ABSTRACT_APACHE_LICENSE_MANAGER_SERVICE_H_
#define _ORG_APACHE_TESTS__SERVICE__ABSTRACT_APACHE_LICENSE_MANAGER_SERVICE_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/service/service.h>

#include "../license.h"

#include "apache_license_manager_service.h"
#include "apache_license_manager_service_request_handler.h"


namespace org {
namespace apache {
namespace tests {
namespace service {
  class AbstractApacheLicenseManagerService : public ApacheLicenseManagerService, public ::naeem::hottentot::runtime::service::Service {
  public:
    AbstractApacheLicenseManagerService() {}
    virtual ~AbstractApacheLicenseManagerService() {}
  public:
    inline virtual uint32_t GetServiceId() const {
      return 3664922178;
    }
  protected:
    inline virtual ::naeem::hottentot::runtime::service::RequestHandler* MakeRequestHandler() {
      return new ApacheLicenseManagerServiceRequestHandler(this);
    }
  };
} // END OF NAMESPACE service
} // END OF NAMESPACE tests
} // END OF NAMESPACE apache
} // END OF NAMESPACE org

#endif