/***********************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 01:59:08
 * Name: apache_license_manager_service_request_handler.h
 * Description:
 *   This file contains definition of service's request handler class.
 ***********************************************************************/

#ifndef _ORG_APACHE_TESTS__SERVICE__APACHE_LICENSE_MANAGER_SERVICE_REQUEST_HANDLER_H_
#define _ORG_APACHE_TESTS__SERVICE__APACHE_LICENSE_MANAGER_SERVICE_REQUEST_HANDLER_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/service/request_handler.h>


namespace org {
namespace apache {
namespace tests {
namespace service {
  class ApacheLicenseManagerServiceRequestHandler : public ::naeem::hottentot::runtime::service::RequestHandler {
  public:
    ApacheLicenseManagerServiceRequestHandler(::naeem::hottentot::runtime::service::Service *service)
      : ::naeem::hottentot::runtime::service::RequestHandler(service) {
    }
    virtual ~ApacheLicenseManagerServiceRequestHandler() {}
  public:
    virtual void HandleRequest(::naeem::hottentot::runtime::Request &request,
                                                   ::naeem::hottentot::runtime::Response &response);
  };
} // END OF NAMESPACE service
} // END OF NAMESPACE tests
} // END OF NAMESPACE apache
} // END OF NAMESPACE org

#endif