/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 11-02-2016 01:32:49
 * Name: calculator_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <naeem/hottentot/runtime/request.h>
#include <naeem/hottentot/runtime/response.h>

#include "calculator_service_request_handler.h"
#include "abstract_calculator_service.h"
#include "calculator_service.h"
#include "../token.h"
#include "../credential.h"
#include "../date_time.h"


namespace example {
namespace generated {
namespace abc {
namespace xyz {
namespace service {
  void 
  CalculatorServiceRequestHandler::HandleRequest(::naeem::hottentot::runtime::Request &request, ::naeem::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 546185601) {
      ::example::generated::abc::xyz::service::AbstractCalculatorService *serviceObject = 
        dynamic_cast< ::example::generated::abc::xyz::service::AbstractCalculatorService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::UInt32 a;
      a.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      ::naeem::hottentot::runtime::types::UInt32 b;
      b.Deserialize(request.GetArgumentData(1), request.GetArgumentLength(1));
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::service::HotContext hotContext;
      ::naeem::hottentot::runtime::types::UInt32 result;
      serviceObject->Add(a, b, result, hotContext);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE xyz
} // END OF NAMESPACE abc
} // END OF NAMESPACE generated
} // END OF NAMESPACE example