/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 10-02-2016 03:06:23
 * Name: tech_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <naeem/hottentot/runtime/request.h>
#include <naeem/hottentot/runtime/response.h>

#include "tech_service_request_handler.h"
#include "abstract_tech_service.h"
#include "tech_service.h"



namespace ir {
namespace ntnaeem {
namespace hottentot {
namespace examples {
namespace tech {
namespace service {
  void 
  TechServiceRequestHandler::HandleRequest(::naeem::hottentot::runtime::Request &request, ::naeem::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 3912715844) {
      ::ir::ntnaeem::hottentot::examples::tech::service::AbstractTechService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::hottentot::examples::tech::service::AbstractTechService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::Utf8String message;
      message.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::service::HotContext hotContext;
      serviceObject->Report(message, hotContext);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = 0;
      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 2183351020) {
      ::ir::ntnaeem::hottentot::examples::tech::service::AbstractTechService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::hottentot::examples::tech::service::AbstractTechService*>(service_);
      /*
       * Deserialization and making input variables
       */
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::service::HotContext hotContext;
      ::naeem::hottentot::runtime::types::Int16 result;
      serviceObject->GetSerial(result, hotContext);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE tech
} // END OF NAMESPACE examples
} // END OF NAMESPACE hottentot
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir